### PR TITLE
Migrate to permission backend

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by mbarbero** [comment]
Thanks for the patch. Well appreciated.

Could you please sign the Eclipse Contributor agreement so I can merge your contribution (https://accounts.eclipse.org/user/eca)? Thanks.

**Comment by davido** [comment]
> Could you please sign the Eclipse Contributor agreement so I can merge your contribution (https://accounts.eclipse.org/user/eca)? Thanks.

Actually I have already signed the ECA. As can be seen from Bugzilla. I refreshed it again.

**Comment by davido** [comment]
@msohn: I think I my email address in this PR is different from one I signed the ECA, so that we have a mismatch. On Gerrit@JGit it works, because I added additional emails there and we have a match.

How can I add another email address in GitHub ECA Check bot? Is this possible I would rather not signed yet another ECA for different mail address, and I would rather not change my email address of this PR.

**Comment by davido** [comment]
Why is this plugin is not hosted on JGit Gerrit? It is Gerrit plugin after all, so why or why other hundreds on Eclipse projects are hosted on Gerrit, but not the Gerrit plugin project?

**Comment by mbarbero** [comment]
> How can I add another email address in GitHub ECA Check bot? If this is possible I would rather not sign yet another ECA for different mail address, and I would rather not change my email address of this PR.

Unfortunately, you cannot add multiple email addresses to your eclipse account. So you will have to either edit this commit to change the author/sign-off email to match the one from your eclipse account or you will have to change the email address associated with your eclipse account. Sorry about that.

> Why this plugin is not hosted on JGit Gerrit? It is Gerrit plugin after all, so why or why other hundreds on Eclipse projects are hosted on Gerrit, but not the Gerrit plugin project?

For historical reasons. Also, it's here because it's not developed under the scope of an Eclipse Project, but by the Eclipse Foundation staff (note the org of this repo is _EclipseFdn_ not _eclipse_). It's been decided a while ago that it should preferably happen on GitHub rather than on Gerrit.

**Comment by davido** [comment]
> Unfortunately, you cannot add multiple email addresses to your eclipse account. 

Thanks for clarifying. I signed yet another ECA and added Signed-off-by footer.

**Comment by mbarbero** [comment]
Thanks for your contribution.

**Pull request merged**
