### PR TITLE
Update to make use of the ECA validation service for business logic

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
@mbarbero could I get some help in testing this/updating my local to test? I have the running Gerrit instance, and have a working LDAP linked. I'm unable to make new projects though, so I can't test the new code properly, and I can't quite figure out the issue. We can set up a short meeting in the next week or so when you have time to unblock this, if that works for you?

**Comment by autumnfound** [comment]
@mbarbero I've been unblocked on the Gerrit side by Dennis (thanks!), but I'm now blocked by the undocumented build process. I don't have the generated sources for the plugin, which is causing compilation failures in maven. From what I can tell, I should have a gradle build (or something similar) to trigger the auto-processor for AutoMoshi shenanigans. This is blocking my testing at this point. 

Do we still need this? Or can we convert to a processor that is less...black magic? From what I can tell it is needed for some special edge cases in HTTP communications, but we now have a pretty basic case...This stuff is 3-4 layers deep in a lib I have 0 familiarity with so I have honestly no idea where to start to even figure out if my guess is right.

**Comment by mbarbero** [comment]
As we found out during our call today, new POJOs need to be generated by AutoValue in order to be usable by retrofit and make the whole project compilable.

**Comment by chrisguindon** [comment]
@mbarbero @autumnfound 

I think we should install this on Foundation Gerrit for testing before we deploy this on production.

**Review by mbarbero — APPROVED** [review]
lgtm

**Comment by mbarbero** [comment]
> @mbarbero @autumnfound
> 
> I think we should install this on Foundation Gerrit for testing before we deploy this on production.

I agree. You will need to engage with either Matt or Denis, as I don't have access to Foundation's gerrit system.

**Comment by chrisguindon** [comment]
> > @mbarbero @autumnfound
> > I think we should install this on Foundation Gerrit for testing before we deploy this on production.
> 
> I agree. You will need to engage with either Matt or Denis, as I don't have access to Foundation's gerrit system.

This was discussed in our weekly team meeting! 

@autumnfound Can you open an infra bug and make sure that @eclipsewebmaster  is //cc on this?

**Pull request merged**
