### PR TITLE
Bug 565601 - Use bots API to check if user is a registered bot and as…

### PR DESCRIPTION
**Pull request by mbarbero**
… such does not need an ECA on file

### CODE REVIEW

**Comment by mbarbero** [comment]
@chrisguindon @autumnfound, I know we will eventually use the centralized service for ECA validation which itself query the bot api. This PR is to fix https://bugs.eclipse.org/565601 quickly.

**Comment by mbarbero** [comment]
(btw, the issue is due to the fact that in previous version of the plugin, we were not checking for ECA if the author had push permission to the repo, i.e. committers and bots via LDAP groups membership)

**Comment by davido** [comment]
> (btw, the issue is due to the fact that in previous version of the plugin, we were not checking for ECA if the author had push permission to the repo, i.e. committers and bots via LDAP groups membership)

Ah, yes, good point. This is definitely a regression from previous plugin behavior.  Another option would be to check if the user in a "Non-Interactive Users" group. See similar check in Gerrit core: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/276358

**Comment by chrisguindon** [comment]
Is it expected that the travis builds are failing?

**Comment by mbarbero** [comment]
> Is it expected that the travis builds are failing?

Yes. Travis integratino should be removed.

**Pull request merged**
